export { default as ScreenShotsCarousel } from "./ScreenShotsCarousel"
export { default as CoverAndTitle } from "./CoverAndTilte"
export { default as InfoChips } from "./InfoChips"
export { default as Summary } from "./Summary"
export { default as Platforms } from "./Platforms"
export { default as SimilarGames } from "./SimilarGames"
export { default as LinkBack } from "./linkBack"
